### ISSUE TITLE
[요청] DOGE, XRP 코인 추가

### ISSUE THREAD

**Issue by jhonverkim** [msaltnet/smtm#32]
DOGE, XRP 코인 추가 부탁드립니다.

**Comment by msaltnet** [comment]
검토해 보겠습니다.

2022년 4월 27일 (수) 오전 9:36, JVK ***@***.***>님이 작성:

**Comment by msaltnet** [comment]
d268a2a1bb0cf5b033b6ac5269ebbb8ce53ef0fc
반영완료!
