### ISSUE TITLE
10분봉, 일봉을 사용할 수 있게 해주세요.

### ISSUE THREAD

**Issue by johnverkim** [msaltnet/smtm#35]
10분봉, 일봉을 사용해서 거래 할 수 있게 해주세요.

**Comment by msaltnet** [comment]
문제가 되는 부분은, Data Provider, Data Repository 부분인것 같아요. 실제 지금 시뮬레이션의 경우도 0.001 term으로 진행을 하여도 Data Provider의 데이터는 분봉이기에 아무런 문제가 없거든요.
요즘 조금 바빠서 수정을 못하고 있는데, 10월 쯤에 한 번 기능을 추가해보겠습니다.

**Comment by msaltnet** [comment]
v1.3.0 버전에서 기능이 추가되었습니다. 기존에도 interval 변경은 가능하였지만, simulation이나 virtual market, controller 등에서 세부 동작이 interval이 자유롭게 변경되기 힘든 구조였습니다. `Config` 모듈을 추가하여 전역에서 candle interval을 설정하고, 나머지 모듈들은 `Config`모듈의 설정값을 참조해서 동작하도록 구조를 변경, 수정하였습니다.

**Simulation, Mass simulation, TelegramController 실전거래 1주일 검증 완료.**
