### ISSUE TITLE
일봉으로 전략 시뮬레이션을 수행 및 실제 트레이딩은 어떻게 하나요?

### ISSUE THREAD

**Issue by hermian** [msaltnet/smtm#45]
일봉으로 전략을 시뮬레이션하고 실 매매를 하려면 어떻게 해야 하는지요?

**Comment by msaltnet** [comment]
일봉으로 시뮬레이션하고, 실 매매도 일봉으로 하는 것인가요?
일봉으로 시뮬레이션하기 위해서는 코드를 조금 수정하면 됩니다. 그런 경우가 드물어서 현재 추가는 안되어 있는데, 어렵지는 않습니다. 실 매매는 더욱 간단한데, 필요하시면 샘플코드 붙여드릴까요?
